baseURL = "https://cspoppuppy.github.io/caveman-news/"
languageCode = "en-gb"
title = "🪨 Caveman News"
disableHugoGeneratorInject = true

[outputs]
  home = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  category = "categories"
